#encoding: utf-8
chengdu = City.where(:name => '成都').first
changan = City.where(:name => '长安').first
quanzhou = City.where(:name => '泉州').first
yangzhou = City.where(:name => '扬州').first
suzhou = City.where(:name => '苏州').first
taiyuan = City.where(:name => '太原').first
changsha = City.where(:name => '长沙').first
fuling = City.where(:name => '涪陵').first
youzhou = City.where(:name => '幽州').first
hangzhou = City.where(:name => '杭州').first
luoyang = City.where(:name => '洛阳').first
lingwu = City.where(:name => '灵武').first
yanmen = City.where(:name => '雁门').first
jiangling = City.where(:name => '江陵').first
yiling = City.where(:name => '夷陵').first
xiangyang = City.where(:name => '襄阳').first
tianshui = City.where(:name => '天水').first
dunhuang = City.where(:name => '敦煌').first
jiangxia = City.where(:name => '江夏').first
poyang = City.where(:name => '鄱阳').first
nanhai = City.where(:name => '南海').first
qiongshan = City.where(:name => '琼山').first

rice = Product.where(:name => '大米').first
sausage = Product.where(:name => '香肠').first
horse = Product.where(:name => '马').first
pig = Product.where(:name => '猪').first
fen_alcohol = Product.where(:name => '汾酒').first
wine = Product.where(:name => '葡萄酒').first
embroidery = Product.where(:name => '刺绣').first
silk = Product.where(:name => '丝绸').first
ceramics = Product.where(:name => '瓷器').first
paint = Product.where(:name => '山水画').first
bow = Product.where(:name => '弓').first
sword = Product.where(:name => '长剑').first
san_qi = Product.where(:name => '三七').first
di_huang = Product.where(:name => '地黄').first
mu_dan = Product.where(:name => '牡丹').first
du_juan = Product.where(:name => '杜鹃').first
hu_qin = Product.where(:name => '胡琴').first
er_hu = Product.where(:name => '二胡').first
litchi = Product.where(:name => '荔枝').first
grape = Product.where(:name => '葡萄').first
paper = Product.where(:name => '纸').first
rouge = Product.where(:name => '胭脂').first

chengdu.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 313)
chengdu.city_product_relations.create(product_id: sausage.id, base_amount: 23, base_price: 421)
chengdu.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 950)
chengdu.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 583)
chengdu.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 360)
chengdu.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 608)
chengdu.city_product_relations.create(product_id: embroidery.id, base_amount: 12, base_price: 912)
chengdu.city_product_relations.create(product_id: silk.id, base_amount: 32, base_price: 516)
chengdu.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 664)
chengdu.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1600)
chengdu.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 975)
chengdu.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1195)
chengdu.city_product_relations.create(product_id: san_qi.id, base_amount: 34, base_price: 145)
chengdu.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 227)
chengdu.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 745)
chengdu.city_product_relations.create(product_id: du_juan.id, base_amount: 38, base_price: 700)
chengdu.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2930)
chengdu.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1680)
chengdu.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 473)
chengdu.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 580)
chengdu.city_product_relations.create(product_id: paper.id, base_amount: 50, base_price: 554)
chengdu.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 960)

changan.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 311)
changan.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 471)
changan.city_product_relations.create(product_id: horse.id, base_amount: 5, base_price: 903)
changan.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 604)
changan.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 377)
changan.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 620)
changan.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 946)
changan.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 565)
changan.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 671)
changan.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1625)
changan.city_product_relations.create(product_id: bow.id, base_amount: 23, base_price: 898)
changan.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1177)
changan.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 154)
changan.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 225)
changan.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 734)
changan.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 793)
changan.city_product_relations.create(product_id: hu_qin.id, base_amount: 6, base_price: 2757)
changan.city_product_relations.create(product_id: er_hu.id, base_amount: 11, base_price: 1550)
changan.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 470)
changan.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 590)
changan.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 599)
changan.city_product_relations.create(product_id: rouge.id, base_amount: 15, base_price: 890)

quanzhou.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 310)
quanzhou.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 460)
quanzhou.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 994)
quanzhou.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 574)
quanzhou.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 352)
quanzhou.city_product_relations.create(product_id: wine.id, base_amount: 12, base_price: 540)
quanzhou.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 1006)
quanzhou.city_product_relations.create(product_id: silk.id, base_amount: 25, base_price: 511)
quanzhou.city_product_relations.create(product_id: ceramics.id, base_amount: 44, base_price: 602)
quanzhou.city_product_relations.create(product_id: paint.id, base_amount: 10, base_price: 1503)
quanzhou.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 1000)
quanzhou.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1223)
quanzhou.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 161)
quanzhou.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 216)
quanzhou.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 733)
quanzhou.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 784)
quanzhou.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3001)
quanzhou.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1704)
quanzhou.city_product_relations.create(product_id: litchi.id, base_amount: 50, base_price: 439)
quanzhou.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 603)
quanzhou.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 593)
quanzhou.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 973)

yangzhou.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 309)
yangzhou.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 452)
yangzhou.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 983)
yangzhou.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 616)
yangzhou.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 368)
yangzhou.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 598)
yangzhou.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 970)
yangzhou.city_product_relations.create(product_id: silk.id, base_amount: 20, base_price: 517)
yangzhou.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 680)
yangzhou.city_product_relations.create(product_id: paint.id, base_amount: 9, base_price: 1526)
yangzhou.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 993)
yangzhou.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1235)
yangzhou.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 160)
yangzhou.city_product_relations.create(product_id: di_huang.id, base_amount: 37, base_price: 204)
yangzhou.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 702)
yangzhou.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 795)
yangzhou.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2920)
yangzhou.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1680)
yangzhou.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 477)
yangzhou.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 596)
yangzhou.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 601)
yangzhou.city_product_relations.create(product_id: rouge.id, base_amount: 26, base_price: 882)

suzhou.city_product_relations.create(product_id: rice.id, base_amount: 30, base_price: 293)
suzhou.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 467)
suzhou.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 940)
suzhou.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 605)
suzhou.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 362)
suzhou.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 610)
suzhou.city_product_relations.create(product_id: embroidery.id, base_amount: 24, base_price: 893)
suzhou.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 561)
suzhou.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 692)
suzhou.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1588)
suzhou.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 950)
suzhou.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1179)
suzhou.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 150)
suzhou.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 219)
suzhou.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 729)
suzhou.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 803)
suzhou.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2952)
suzhou.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1698)
suzhou.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 463)
suzhou.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 567)
suzhou.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 617)
suzhou.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 990)

taiyuan.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 311)
taiyuan.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 483)
taiyuan.city_product_relations.create(product_id: horse.id, base_amount: 8, base_price: 872)
taiyuan.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 601)
taiyuan.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 26, base_price: 331)
taiyuan.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 602)
taiyuan.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 990)
taiyuan.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 574)
taiyuan.city_product_relations.create(product_id: ceramics.id, base_amount: 36, base_price: 604)
taiyuan.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1569)
taiyuan.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 998)
taiyuan.city_product_relations.create(product_id: sword.id, base_amount: 20, base_price: 1087)
taiyuan.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 150)
taiyuan.city_product_relations.create(product_id: di_huang.id, base_amount: 24, base_price: 208)
taiyuan.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 698)
taiyuan.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 801)
taiyuan.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2968)
taiyuan.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1713)
taiyuan.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 471)
taiyuan.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 566)
taiyuan.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 623)
taiyuan.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 975)

changsha.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 316)
changsha.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 487)
changsha.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 976)
changsha.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 589)
changsha.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 363)
changsha.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 613)
changsha.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 954)
changsha.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 598)
changsha.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 659)
changsha.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1520)
changsha.city_product_relations.create(product_id: bow.id, base_amount: 19, base_price: 891)
changsha.city_product_relations.create(product_id: sword.id, base_amount: 27, base_price: 1102)
changsha.city_product_relations.create(product_id: san_qi.id, base_amount: 40, base_price: 138)
changsha.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 218)
changsha.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 711)
changsha.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 799)
changsha.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2989)
changsha.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1697)
changsha.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 469)
changsha.city_product_relations.create(product_id: grape.id, base_amount: 36, base_price: 544)
changsha.city_product_relations.create(product_id: paper.id, base_amount: 24, base_price: 567)
changsha.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 984)

fuling.city_product_relations.create(product_id: rice.id, base_amount: 47, base_price: 287)
fuling.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 456)
fuling.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 988)
fuling.city_product_relations.create(product_id: pig.id, base_amount: 20, base_price: 555)
fuling.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 373)
fuling.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 568)
fuling.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 921)
fuling.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 588)
fuling.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 642)
fuling.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1573)
fuling.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 942)
fuling.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1200)
fuling.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 159)
fuling.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 221)
fuling.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 696)
fuling.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 747)
fuling.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3080)
fuling.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1701)
fuling.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 460)
fuling.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 560)
fuling.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 598)
fuling.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 950)

youzhou.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 313)
youzhou.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 466)
youzhou.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 950)
youzhou.city_product_relations.create(product_id: pig.id, base_amount: 23, base_price: 560)
youzhou.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 345)
youzhou.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 601)
youzhou.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 945)
youzhou.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 579)
youzhou.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 666)
youzhou.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1590)
youzhou.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 976)
youzhou.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1169)
youzhou.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 161)
youzhou.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 228)
youzhou.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 700)
youzhou.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 810)
youzhou.city_product_relations.create(product_id: hu_qin.id, base_amount: 4, base_price: 2790)
youzhou.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1659)
youzhou.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 470)
youzhou.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 583)
youzhou.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 603)
youzhou.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 998)

hangzhou.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 313)
hangzhou.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 463)
hangzhou.city_product_relations.create(product_id: horse.id, base_amount: 6, base_price: 910)
hangzhou.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 596)
hangzhou.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 350)
hangzhou.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 612)
hangzhou.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 968)
hangzhou.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 564)
hangzhou.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 647)
hangzhou.city_product_relations.create(product_id: paint.id, base_amount: 18, base_price: 1520)
hangzhou.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 986)
hangzhou.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1190)
hangzhou.city_product_relations.create(product_id: san_qi.id, base_amount: 38, base_price: 143)
hangzhou.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 217)
hangzhou.city_product_relations.create(product_id: mu_dan.id, base_amount: 24, base_price: 654)
hangzhou.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 782)
hangzhou.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3097)
hangzhou.city_product_relations.create(product_id: er_hu.id, base_amount: 20, base_price: 1549)
hangzhou.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 477)
hangzhou.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 597)
hangzhou.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 610)
hangzhou.city_product_relations.create(product_id: rouge.id, base_amount: 18, base_price: 900)

luoyang.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 309)
luoyang.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 488)
luoyang.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 968)
luoyang.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 613)
luoyang.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 19, base_price: 328)
luoyang.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 609)
luoyang.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 937)
luoyang.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 562)
luoyang.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 694)
luoyang.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1541)
luoyang.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 944)
luoyang.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1210)
luoyang.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 154)
luoyang.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 220)
luoyang.city_product_relations.create(product_id: mu_dan.id, base_amount: 40, base_price: 649)
luoyang.city_product_relations.create(product_id: du_juan.id, base_amount: 31, base_price: 704)
luoyang.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3049)
luoyang.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1723)
luoyang.city_product_relations.create(product_id: litchi.id, base_amount: 33, base_price: 439)
luoyang.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 600)
luoyang.city_product_relations.create(product_id: paper.id, base_amount: 30, base_price: 560)
luoyang.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 942)

lingwu.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 307)
lingwu.city_product_relations.create(product_id: sausage.id, base_amount: 30, base_price: 438)
lingwu.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 975)
lingwu.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 606)
lingwu.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 358)
lingwu.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 592)
lingwu.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 989)
lingwu.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 580)
lingwu.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 688)
lingwu.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1612)
lingwu.city_product_relations.create(product_id: bow.id, base_amount: 30, base_price: 887)
lingwu.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1246)
lingwu.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 158)
lingwu.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 224)
lingwu.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 720)
lingwu.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 772)
lingwu.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2974)
lingwu.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1678)
lingwu.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 468)
lingwu.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 587)
lingwu.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 595)
lingwu.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 939)

yanmen.city_product_relations.create(product_id: rice.id, base_amount: 37, base_price: 290)
yanmen.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 485)
yanmen.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 988)
yanmen.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 607)
yanmen.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 368)
yanmen.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 595)
yanmen.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 972)
yanmen.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 569)
yanmen.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 679)
yanmen.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1584)
yanmen.city_product_relations.create(product_id: bow.id, base_amount: 19, base_price: 892)
yanmen.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1238)
yanmen.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 160)
yanmen.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 217)
yanmen.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 742)
yanmen.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 767)
yanmen.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3014)
yanmen.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1647)
yanmen.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 466)
yanmen.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 577)
yanmen.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 614)
yanmen.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 970)

jiangling.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 309)
jiangling.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 478)
jiangling.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 949)
jiangling.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 595)
jiangling.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 370)
jiangling.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 611)
jiangling.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 990)
jiangling.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 597)
jiangling.city_product_relations.create(product_id: ceramics.id, base_amount: 21, base_price: 618)
jiangling.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1596)
jiangling.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 954)
jiangling.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1185)
jiangling.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 159)
jiangling.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 226)
jiangling.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 738)
jiangling.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 800)
jiangling.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3044)
jiangling.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1725)
jiangling.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 482)
jiangling.city_product_relations.create(product_id: grape.id, base_amount: 24, base_price: 541)
jiangling.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 600)
jiangling.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 963)

xiangyang.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 310)
xiangyang.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 459)
xiangyang.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 982)
xiangyang.city_product_relations.create(product_id: pig.id, base_amount: 31, base_price: 558)
xiangyang.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 369)
xiangyang.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 618)
xiangyang.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 934)
xiangyang.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 590)
xiangyang.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 674)
xiangyang.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1537)
xiangyang.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 968)
xiangyang.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1164)
xiangyang.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 152)
xiangyang.city_product_relations.create(product_id: di_huang.id, base_amount: 29, base_price: 199)
xiangyang.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 725)
xiangyang.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 794)
xiangyang.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2986)
xiangyang.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1648)
xiangyang.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 464)
xiangyang.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 591)
xiangyang.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 608)
xiangyang.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 977)

tianshui.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 305)
tianshui.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 458)
tianshui.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 1000)
tianshui.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 588)
tianshui.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 20, base_price: 332)
tianshui.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 584)
tianshui.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 958)
tianshui.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 570)
tianshui.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 690)
tianshui.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1566)
tianshui.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 992)
tianshui.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1206)
tianshui.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 158)
tianshui.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 220)
tianshui.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 714)
tianshui.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 757)
tianshui.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2997)
tianshui.city_product_relations.create(product_id: er_hu.id, base_amount: 17, base_price: 1540)
tianshui.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 473)
tianshui.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 595)
tianshui.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 618)
tianshui.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 993)

dunhuang.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 308)
dunhuang.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 478)
dunhuang.city_product_relations.create(product_id: horse.id, base_amount: 10, base_price: 885)
dunhuang.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 599)
dunhuang.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 371)
dunhuang.city_product_relations.create(product_id: wine.id, base_amount: 14, base_price: 556)
dunhuang.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 941)
dunhuang.city_product_relations.create(product_id: silk.id, base_amount: 18, base_price: 529)
dunhuang.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 654)
dunhuang.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1616)
dunhuang.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 973)
dunhuang.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1228)
dunhuang.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 159)
dunhuang.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 221)
dunhuang.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 705)
dunhuang.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 762)
dunhuang.city_product_relations.create(product_id: hu_qin.id, base_amount: 12, base_price: 2720)
dunhuang.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1690)
dunhuang.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 478)
dunhuang.city_product_relations.create(product_id: grape.id, base_amount: 44, base_price: 539)
dunhuang.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 596)
dunhuang.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 987)

jiangxia.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 315)
jiangxia.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 469)
jiangxia.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 965)
jiangxia.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 600)
jiangxia.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 369)
jiangxia.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 604)
jiangxia.city_product_relations.create(product_id: embroidery.id, base_amount: 16, base_price: 912)
jiangxia.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 582)
jiangxia.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 650)
jiangxia.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1547)
jiangxia.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 960)
jiangxia.city_product_relations.create(product_id: sword.id, base_amount: 16, base_price: 1114)
jiangxia.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 154)
jiangxia.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 219)
jiangxia.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 694)
jiangxia.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 789)
jiangxia.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3067)
jiangxia.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1712)
jiangxia.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 480)
jiangxia.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 588)
jiangxia.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 606)
jiangxia.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 923)

poyang.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 308)
poyang.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 489)
poyang.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 943)
poyang.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 592)
poyang.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 359)
poyang.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 612)
poyang.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 983)
poyang.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 593)
poyang.city_product_relations.create(product_id: ceramics.id, base_amount: 28, base_price: 600)
poyang.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1578)
poyang.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 928)
poyang.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1165)
poyang.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 155)
poyang.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 226)
poyang.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 707)
poyang.city_product_relations.create(product_id: du_juan.id, base_amount: 25, base_price: 705)
poyang.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3025)
poyang.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1738)
poyang.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 468)
poyang.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 572)
poyang.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 586)
poyang.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 947)

nanhai.city_product_relations.create(product_id: rice.id, base_amount: 0, base_price: 312)
nanhai.city_product_relations.create(product_id: sausage.id, base_amount: 35, base_price: 439)
nanhai.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 991)
nanhai.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 608)
nanhai.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 367)
nanhai.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 618)
nanhai.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 977)
nanhai.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 566)
nanhai.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 661)
nanhai.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1586)
nanhai.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 937)
nanhai.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1196)
nanhai.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 162)
nanhai.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 218)
nanhai.city_product_relations.create(product_id: mu_dan.id, base_amount: 0, base_price: 719)
nanhai.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 811)
nanhai.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 2983)
nanhai.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1688)
nanhai.city_product_relations.create(product_id: litchi.id, base_amount: 42, base_price: 430)
nanhai.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 579)
nanhai.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 589)
nanhai.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 965)

qiongshan.city_product_relations.create(product_id: rice.id, base_amount: 40, base_price: 291)
qiongshan.city_product_relations.create(product_id: sausage.id, base_amount: 0, base_price: 478)
qiongshan.city_product_relations.create(product_id: horse.id, base_amount: 0, base_price: 987)
qiongshan.city_product_relations.create(product_id: pig.id, base_amount: 0, base_price: 618)
qiongshan.city_product_relations.create(product_id: fen_alcohol.id, base_amount: 0, base_price: 350)
qiongshan.city_product_relations.create(product_id: wine.id, base_amount: 0, base_price: 608)
qiongshan.city_product_relations.create(product_id: embroidery.id, base_amount: 0, base_price: 928)
qiongshan.city_product_relations.create(product_id: silk.id, base_amount: 0, base_price: 590)
qiongshan.city_product_relations.create(product_id: ceramics.id, base_amount: 0, base_price: 649)
qiongshan.city_product_relations.create(product_id: paint.id, base_amount: 0, base_price: 1576)
qiongshan.city_product_relations.create(product_id: bow.id, base_amount: 0, base_price: 990)
qiongshan.city_product_relations.create(product_id: sword.id, base_amount: 0, base_price: 1233)
qiongshan.city_product_relations.create(product_id: san_qi.id, base_amount: 0, base_price: 157)
qiongshan.city_product_relations.create(product_id: di_huang.id, base_amount: 0, base_price: 224)
qiongshan.city_product_relations.create(product_id: mu_dan.id, base_amount: 22, base_price: 666)
qiongshan.city_product_relations.create(product_id: du_juan.id, base_amount: 0, base_price: 808)
qiongshan.city_product_relations.create(product_id: hu_qin.id, base_amount: 0, base_price: 3048)
qiongshan.city_product_relations.create(product_id: er_hu.id, base_amount: 0, base_price: 1694)
qiongshan.city_product_relations.create(product_id: litchi.id, base_amount: 0, base_price: 471)
qiongshan.city_product_relations.create(product_id: grape.id, base_amount: 0, base_price: 570)
qiongshan.city_product_relations.create(product_id: paper.id, base_amount: 0, base_price: 590)
qiongshan.city_product_relations.create(product_id: rouge.id, base_amount: 0, base_price: 958)