development:
  adapter: postgresql
  database: bon_voyage
  host: localhost
  reconnect: true
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bon_voyage_test
  host: localhost
  reconnect: true
  pool: 5
  timeout: 5000

